routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout');




            
Route::get('/', function () {
    // return view('admin.pages.dashboard.dashboard');
    return "this is front end";
})->middleware('auth');
Route::get('dashboard','Admin\DashboardController@index')->name('category.home')->middleware('auth');
// Route::get('admin/cat/up/{id}','Admin\CategoryController@catup')->name('cat.up');

Route::prefix('admin')->group(function(){
    Route::group(['middleware' => 'auth'],function () {
        Route::resource('doctor-category', 'Admin\CategoryController');
        Route::resource('appointment', 'Admin\AppointmentController');
        Route::resource('doctor', 'Admin\DoctorController');
        Route::resource('shedule', 'Admin\SheduleController');
        Route::resource('about/mission', 'Admin\aboutus\MissionController');
        Route::resource('about/administration', 'Admin\aboutus\AdministrationController');
        Route::resource('about', 'Admin\aboutus\AboutController');
        Route::resource('facilities', 'Admin\FacilityController');
        Route::resource('dental-college/category', 'Admin\Dental_college\DentalCategoryController');
        Route::resource('dental-college/post', 'Admin\Dental_college\DentalPostController');
    });
});
   

app/Http/Controllers/Admin/facilityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Admin\facility;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class facilityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['facilities'] = facility::all();
        return view('admin.pages.facilities.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
         'title'=>'required',
         'facilities'=>'required',
        ]);
        $facilities = new facility();
        $facilities->title = $request->title;
        $facilities->description = $request->description;
        $facilities->facilities = $request->facilities;
        $facilities->save();
        Toastr::success('Success','Facilities Stored successfully');
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $data['item']= facility::find($id);
        return view('admin.pages.facilities.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $request->validate([
            'title'=>'required',
            'facilities'=>'required',
           ]);
           $facilities = facility::find($id);
           $facilities->title = $request->title;
           $facilities->description = $request->description;
           $facilities->facilities = $request->facilities;
           $facilities->save();
           Toastr::success('Success','Facilities Updated successfully');
           return redirect()->route('facilities.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $facilities = facility::find($id);
        $facilities->delete();
        Toastr::success('Success','Facilities Deleted successfully');
        return redirect()->route('facilities.index');
    }
}

resources/views/admin/pages/facilities/edit.blade.php
@extends('admin.pages.main')
@section('content')
<form role="form" method="POST" action="{{ route('facilities.update',$item->id) }}">
    @csrf
    @method('PUT')
  <div class="card-body">
    <div class="row">
      <div class="col-12 col-md-12"> 
        <div class="form-group">
          <label for="exampleInputEmail1">Title</label>
          <input type="text" class="form-control" name="title" value="{{ $item->title }}">
          @error('title')
          <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        </div>
      </div>

      <div class="col-12 col-md-12">
        <div class="form-group">
            <label for="my-textarea">Description</label>
            <textarea id="my-textarea" class="form-control" name="description" rows="3">
                {{ $item->description }}
            </textarea>
        </div>
       </div>

       <div class="col-12 col-md-12">
          <div class="form-group">
            <label for="exampleInputEmail1">Facilities</label>
            <textarea id="mytextarea" class="form-control" name="facilities" rows="3">
             {{ $item->facilities }}
            </textarea>
                @error('facilities')
                  <div class="alert alert-danger">{{ $message }}</div>
                @enderror
          </div>
       </div>
       
      
    </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <button type="submit" class="btn btn-outline-light">Update</button>
  </div>
</form>
@endsection
@push('js')
    <script>
        tinymce.init({
                        selector: '#mytextarea',
                     });
    </script>
@endpush